# Default database configuration

development:
  adapter: sqlite3
  database: db/development.sqlite3

test:
  adapter: sqlite3
  database: db/test.sqlite3

production:
  adapter: mysql
  database: toycity_production
  username: root
  password: password
  host: localhost
  socket: /var/lib/mysql/mysql.sock